services:
  ecs:
    image: dell/ecs-software:3.8.1.0
    container_name: ecs-instance
    ports:
      - 9020:9020
    environment:
      - ECS_HOST=localhost
      - ECS_MANAGEMENT_ROOT_USER=admin
      - ECS_MANAGEMENT_ROOT_PASSWORD=g0dECS50
      - SS_GENCONFIG=1
    volumes:
      - ./data:/host/data
      - ecs_config:/opt/storageos/conf
      - ecs_bin:/opt/storageos/bin
      - ecs_data:/opt/emc/ecs-install
      - ecs_dae:/dae
    privileged: true

volumes:
  ecs_bin:
  ecs_data:
  ecs_config:
  ecs_dae: