services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: g0dmini0
    command: server --console-address :9001 /data

volumes:
  minio_storage: {}