spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:///dev/urandom -XX:+UseZGC -XX:+UseStringDeduplication"
        - name: SPRING_PROFILES_ACTIVE
          value: default,cloud,openai,pgvector
      - name: pgvector
        image: pgvector/pgvector:pg16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pgvector
        volumeMounts:
        - name: pgvector-data
          mountPath: /var/lib/postgresql/data
        - name: creds-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: pgvector-data
        emptyDir: {}
      - name: creds-volume
        secret:
          secretName: spring-ai-creds
          items:
          - key: creds.yml
            path: creds.yml
